CREATE TABLE documents (
  document_id TEXT PRIMARY KEY,
  collection_id TEXT NOT NULL REFERENCES collections ON DELETE CASCADE ON UPDATE CASCADE,
  created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW()
);