CREATE TABLE document_field_values (
  value TEXT NOT NULL,
  document_id TEXT NOT NULL REFERENCES documents ON DELETE CASCADE ON UPDATE CASCADE,
  field_id TEXT NOT NULL REFERENCES fields ON DELETE CASCADE ON UPDATE CASCADE,
  created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
  PRIMARY KEY (document_id, field_id)
);